### ISSUE TITLE
Frosty 1.0.4.2 error

### ISSUE THREAD

**Issue by S7Hoxworth** [GalaxyEham/FrostyToolSuite#107]
"There was an error when trying to load game using specified profile" I get this error every time i select a game exe

**Comment by GalaxyEham** [comment]
which game?

**Comment by S7Hoxworth** [comment]
Star Wars BFII

**Comment by GalaxyEham** [comment]
Redownload mod manager, I missed a file the first time i uploaded

**Comment by S7Hoxworth** [comment]
It still happens I didn't have this problem with the older  managers

**Comment by GalaxyEham** [comment]
well nothing really changed about the profiles, so if ur confident that ur extracting the contents correctly, no files are missing, and ur not simply overwriting an older version, then theres really no reason for it not to work, and really I have nothing to go off

**Comment by S7Hoxworth** [comment]
No files are missing im not overwriting an older version i have no idea why this happens it doesnt give me any error codes to

**Comment by time96** [comment]
yea im having the same issue it would be great if you could help me.

Error:
"There was an error when trying to load game using specified profile"

SWBF2

**Comment by ZestyCuort** [comment]
HOLY CRAP I GOT IT! quit origin completely. -_-

**Comment by time96** [comment]
nope not working

**Comment by S7Hoxworth** [comment]
You mean like logout?

**Comment by S7Hoxworth** [comment]
Still doesn't work

**Comment by time96** [comment]
anyone found solution yet?

**Comment by strangermoon** [comment]
hi every one. ı manage to fix with my own thing for battlefront 2 this error and works 100.  you need ini file. ı put this nexus site. 
https://www.nexusmods.com/starwarsbattlefront22017/mods/919/

downaload ini file put the ini file to your froty mod manager 1.04.2 file. then open ini file  change gamepat:= to your battlefront 2 location. you can check on shoutcut the trick here dont write  "2" you need to write "II"
for example my now  : 
GamePath=D:\Games\STAR WARS Battlefront II

and works.  
how ı crate this in file is ı try to open battlefont 2015 exe instead of and it succeed and created ini file then ı changed to ini file all battlefront 2015 with battleront II.

ı tryed with amazing battle of endor mod it works. have nice day it has been a problme for me to since may end everyday ı check here so ı put here.

**Comment by S7Hoxworth** [comment]
Thank you so much

2018-08-15 3:07 GMT+03:00 strangermoon <notifications@github.com>:
