### ISSUE TITLE
doesn't work with bf3, bf4, bfhl or moh warfighter

### ISSUE THREAD

**Issue by rancorx2** [GalaxyEham/FrostyToolSuite#134]
hi, any chance of getting support added for all the frostbite battlefield games and moh warfighter?

wanna mod them and disable the postfx.

**Comment by GalaxyEham** [comment]
By design, Frosty will never work with BF3, too old, runs on a different version of the Frostbite engine. Frosty will only support Frostbite 3 games, BF4 support will most likely come at some stage, but due to its age it'll take time, a lot has changed even in Frostbite 3's lifespan, the other two, no idea
