### ISSUE TITLE
Debug ModManager on Wine

### ISSUE THREAD

**Issue by t14462** [GalaxyEham/FrostyToolSuite#162]
You have some weird HLSL shader, which crashing on Wine in Linux with error about d3dCompiler

Please check it

My DX9 version is gallium nine (native linux), d3dcompiler is builtin

**Comment by t14462** [comment]
When I installed d3dcompiler_47 - it works

**Comment by t14462** [comment]
It only shows window, but everything not OK

**Comment by GalaxyEham** [comment]
Closing ticket, Editor/Mod Manager are not supported on Wine, if you manage to find workarounds that is fine, but I will not add them to requirements.

**Comment by t14462** [comment]
It's weird! Why mod manager dependent on DX9?! It's just regular program, not a PRO modding tool! It's dumb.

On Gallium Nine with d3dcompiler_47 everything OK, except configurable mods.

All configurable mods crashing MM, but everything else works fine.

Why you dont want debug it on wine? It seems working at-all, just dont be a pig. Debugging installable mod will not hurt you.

**Comment by GalaxyEham** [comment]
WPF uses DX9 to render the windows and controls, so I have no control over that, I also use DX9 to share the back buffer from DX11 so that it can be rendered into a WPF control (given that WPF is built to use DX9). So really has nothing to do with it being a regular or PRO tool.

As for calling me a pig, that is the quickest way for me not to even want to support you, basically its the definition of the saying "biting the hand that feeds you". 

I dont have WINE or LINUX, nor do I want to install them, so therefore it is unsupported, this has nothing to do with "Your way not supported, and we dont care about it" and more to do with time. To install and debug requires time, time that I dont have, and if I go to those lengths, what about other OS configurations ie. Mac and Windows Parallels of which I recently learnt also has issues, again this is unsupported, am I a "pig" for not supporting that either? or is it just because I wont help you?

**Comment by t14462** [comment]
Sorry for that. Forgive me. I was in bad mood & drunk.

I just want to say: your program works fine with native linux DX9 + d3dcompiler.

But configurable mods crashing it. If i find workaround i will tell you.
